#version: '3.8'

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SERVICES
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
services:
  ########################################
  # BACKEND
  ########################################
  backend:
    build: ./backend
    ports:
      - "3000:3000"           # espone porta backend
    volumes:
      - ./backend:/app        # mappa il codice locale nella container
    restart: unless-stopped
    depends_on:
      - mongo  

  ########################################
  # FRONTEND
  ########################################
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"           # espone porta Vite
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  ########################################
  # MONGO DB
  ########################################
  mongo:             
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# VOLUMES
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
volumes:
  mongo_data:      
