version: '3.8'

services:
  ########################################
  # BACKEND
  ########################################
  backend:
    build: ./backend
    ports:
      - "3000:3000"           # espone porta backend
    volumes:
      - ./backend:/app        # mappa il codice locale nella container
    restart: unless-stopped

  ########################################
  # FRONTEND
  ########################################
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"           # espone porta Vite
    volumes:
      - ./frontend:/app
    restart: unless-stopped
